version: "3"
services:
  app:
    build: .
    volumes:
      - .:/dbt
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
