data_warehouse_dbt:
  outputs:
    dev:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
  target: dev
